### ISSUE TITLE
Maximize Windows

### ISSUE THREAD

**Issue by nwrkbiz** [jamesfcarter/lwm#3]
Hello!

I use lwm on a regular basis and i feel really comfortable with it! I use the Package from the Debian 'testing' repository.

There is only one feature I miss (or not aware of): a button (or key combination) to make a window fullscreen.

Is this a feature that makes sense for you? Is worth to spend time on?

Kind regards,
nwrkbiz

**Comment by nwrkbiz** [comment]
Sorry I should have read this first:
http://www.jfc.org.uk/software/lwm-FAQ.html

I use tint2 as a taskbar, so i did not bear in mind, that in an environment without taskbar some space of the root window need to visible. 

a optional setting to enable maximizing windows would be still a nice to have.

**Comment by Docbroke** [comment]
You can use xdotool to maximize windows.

**Comment by nwrkbiz** [comment]
Thanks for the hint, but I switched to pekwm because it features exactly the stuff I need.
